function [SUB] = subjData_WM()
d = dialog('Position',[300 300 250 500],'Name','SubjectData'); 

Weight = ['-', num2cell(40:150)];
Height = ['-',num2cell(140:210)];
Age    = ['-', num2cell(1:120)];
PossibleEducation = ['-', num2cell(1:120)];
SUB = {};

Welcome_txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[15 80 210 400],...
    'String','Please fill in subjects data');

Subject_ID_txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[-15 260 150 200],...
    'String','Subject_ID:');

Subject_ID = uicontrol('Parent',d,...
    'Style','edit',...
    'Position',[32 420 150 20],...
    'String','',...
    'Callback',@popup_Subject_ID);

Group_txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[-20 215 140 200],...
    'String','Group:');

Group = uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[32 375 150 20],...
    'String',{'-';'A';'B'},...  
    'Callback',@popup_Group);

Education_txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[-27 215 170 150],...
    'String','Education:');

Education = uicontrol('Parent',d,...
    'Style','popup',... 
    'Position',[32 295 70 50],...     
    'String',{PossibleEducation{1,:}},...
    'Callback',@popup_Education);

Age_txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[120 315 50 50],...
    'String','Age:');

Age =uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[130 295 70 50],... 
    'String',{Age{1,:}},...
    'Callback',@popup_Age);

Sex_txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[20 265 50 50],...
    'String','Sex:');

Sex =uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[32 245 80 50],... 
    'String',{'-';'Female';'Male'},... 
    'Callback',@popup_Sex);

Laterality_txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[130 265 50 50],...
    'String','Laterality:');

Laterality =uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[130 245 80 50],... 
    'String',{'-';'Left';'Right'},...
    'Callback',@popup_Laterality);

Experience_txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[-30 165 150 100],...
    'String','Exp.:');

Experience = uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[25 210 70 35],... 
    'String',{'-';'No';'Yes'},...
    'Callback',@popup_Experience);

Weight_txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[85 165 40 100],...
    'String','Weight:');

Weight =uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[80 210 70 35],...
    'String',{Weight{1,:}},...
    'Callback',@popup_Weight);

Height_txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[150 240 40 25],...
    'String','Height:');

Height =uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[140 195 80 50],...  
    'String',{Height{1,:}},...
    'Callback',@popup_Height);

Task_Managment_txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[-25 150 300 50],...
    'String','-------------- Finished --------------');

Continuebtn = uicontrol('Parent',d,...
    'Position',[50 20 70 25],...
    'String','Ok',...
    'Callback','close all');


Cancelbtn = uicontrol('Parent',d,...
    'Position',[150 20 70 25],...
    'String','Cancel',...
    'Callback','delete(gcf)');

% Wait for d to close before running to completion
uiwait(d);
    function popup_Subject_ID(Subject_ID, event)
        popup_items = Subject_ID.String;
        SUB{1,1} = popup_items;
    end
    function popup_Group(Group, event)
        idx = Group.Value;
        popup_items = Group.String;
        SUB{2,1} = char(popup_items(idx,:));
    end
    function popup_Education(Education, event)
        idx = Education.Value;
        popup_items = Education.String;
        SUB{3,1} = char(popup_items(idx,:));
    end
    function popup_Age(Age, event)
        idx = Age.Value;
        popup_items = Age.String;
        SUB{4,1} = char(popup_items(idx,:));
    end
    function popup_Sex(Sex, event)
        idx = Sex.Value;
        popup_items = Sex.String;
        SUB{5,1} = char(popup_items(idx,:));
    end
    function popup_Laterality(Laterality, event)
        idx = Laterality.Value;
        popup_items = Laterality.String;
        SUB{6,1} = char(popup_items(idx,:));
    end
    function popup_Experience(Experience, event)
        idx = Experience.Value;
        popup_items = Experience.String;
        SUB{7,1} = char(popup_items(idx,:));
    end
    function popup_Weight(Weight, event)
        idx = Weight.Value;
        popup_items = Weight.String;
        SUB{8,1} = char(popup_items(idx,:));
    end
    function popup_Height(Height, event)
        idx = Height.Value;
        popup_items = Height.String;
        SUB{9,1} = char(popup_items(idx,:));
    end

end
