function [SUB] = subjInfo_WM()
% UIcontrol to get subject information per session of the WM experiment.
% PRG 11/2019

d = dialog('Position',[300 300 250 400],'Name','SubjectInfo');

SUB = {};

Welcome_txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[15 80 210 300],...
    'String','Welcome!, Thanks for participating :)');

Subject_ID_txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[-15 260 150 100],...
    'String','Subject_ID:');

Subject_ID = uicontrol('Parent',d,...
    'Style','edit',...
    'Position',[32 320 150 20],...
    'String',{''}, ...
    'Callback',@popup_Subject_ID);

Session_txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[-20 215 150 100],...
    'String','Session:');

Session = uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[32 275 150 20],...
    'String',{'Perception', 'ShapeOnly','ShapeColor'}, ...
    'Callback',@popup_Session);

Amount_Stimuli_txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[5 165 150 100],...
    'String','Amount_Of_Stimuli:');

Stimuli = uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[32 220 80 25],...
    'String',{'2';'3'},...
    'Callback',@popup_Stimuli);

% Distance_To_Screen_txt = uicontrol('Parent',d,...
%     'Style','text',...
%     'Position',[10 115 150 100],...
%     'String','Distance_To_Screen:');
% 
% Meters_txt = uicontrol('Parent',d,...
%     'Style','text',...
%     'Position',[-25 95 150 100],...
%     'String','Meters:');
% 
% Meters_Distance = uicontrol('Parent',d,...
%     'Style','popup',...
%     'Position',[32 150 40 25],...
%     'String',(0:10),...
%     'Callback',@popup_Meters);
% 
% Centimeters_txt = uicontrol('Parent',d,...
%     'Style','text',...
%     'Position',[100 95 40 100],...
%     'String','Cm:');
% 
% CM_Distance = uicontrol('Parent',d,...
%     'Style','popup',...
%     'Position',[110 150 40 25],...
%     'String',(0:99),...
%     'Callback',@popup_Centimeters);

Version_txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[28 100 60 25],...
    'String','Version:');

Version = uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[32 80 100 25],...
    'String',{'Normal', 'EEG'},...
    'Callback',@popup_Version);

% StartFrom_txt = uicontrol('Parent',d,...
%     'Style','text',...
%     'Position',[28 100 60 25],...
%     'String','StartFrom:');
% 
% StartFrom = uicontrol('Parent',d,...
%     'Style','popup',...
%     'Position',[32 80 100 25],...
%     'String',{'-';'Perception';'Task'},...
%     'Callback',@popup_StartFrom);

Continuebtn = uicontrol('Parent',d,...
    'Position',[50 20 70 25],...
    'String','Ok',...
    'Callback','close all');

Cancelbtn = uicontrol('Parent',d,...
    'Position',[150 20 70 25],...
    'String','Cancel',...
    'Callback','delete(gcf)');

% Wait for d to close before running to completion
uiwait(d);
    function popup_Subject_ID(Subject_ID, event)
        popup_items = Subject_ID.String;
        SUB{1,1} = popup_items;
    end

    function popup_Session(Session, event)
        idx = Session.Value;
        popup_items = Session.String;
        SUB{2,1} = char(popup_items(idx,:));
    end

    function popup_Stimuli(Stimuli, event)
        idx = Stimuli.Value;
        popup_items = Stimuli.String;
        SUB{3,1} = char(popup_items(idx,:));
    end

    function popup_Meters(Meters_Distance, event)
        idx = Meters_Distance.Value;
        popup_items = Meters_Distance.String;
        SUB{4,1} = char(popup_items(idx,:));
    end

    function popup_Centimeters(CM_Distance, event)
        idx = CM_Distance.Value;
        popup_items = CM_Distance.String;
        SUB{5,1} = char(popup_items(idx,:));
    end

    function popup_Version(Version, event)
        idx = Version.Value;
        popup_items = Version.String;
        SUB{6,1} = char(popup_items(idx,:));
    end

%     function popup_StartFrom(StartFrom, event)
%         idx = StartFrom.Value;
%         popup_items = StartFrom.String;
%         SUB{4,1} = char(popup_items(idx,:));
%     end

end
