function [Textos_Percepcion, Textos_Tarea] = Textos_Tareas()
Textos_Percepcion = {['En esta parte de la prueba se le presentar?n unas formas coloreadas en la parte', sprintf('\n'),...
    'superior e inferior de la pantalla.', sprintf('\n'),...    
    sprintf('\n'),...
    sprintf('\n'),...
    'Tendra que decidir si las formas coloreadas que se presentan en la parte superior', sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'de la pantalla son iguales o diferentes a las que aparecen en la parte inferior', sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'Presione espacio para continuar'],...
    ['Si piensa que son IGUALES, presione el "BOTON DERECHO".', sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'Si piensa que son DIFERENTES, presione el "BOTON IZQUIERDO".', sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'La localizaci?n no importa, s?lo la forma y el color de las figuras', sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'conteste lo m?s r?pido y preciso posible. Si tiene dudas consulteme.',sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'Presione espacio para continuar']};
Textos_Tarea = {['En esta parte del test de memoria nos fijaremos en su memoria para las formas.', sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'Durante el test primero ver? una pantalla con tres formas. Trate de recordarlas todas.', sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'Aparecer? una nueva pantalla en la que se le presentar?n tambi?n tres formas.', sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'Su tarea consiste en decir si las formas de la primera y de la segunda pantalla son iguales o diferentes.', sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'La posici?n de las formas en la pantalla cambiar?, por eso no es importante. Lo que importa son las formas.', sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'Veamos c?mo van a aparecer (a ser) las pantallas.',sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'Presione espacio para continuar'],...
    ['Si piensa que son IGUALES, presione el "BOTON DERECHO".', sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'Si piensa que son DIFERENTES, presione el "BOTON IZQUIERDO".', sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'La localizaci?n no importa, s?lo la forma y el color de las figuras', sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'conteste lo m?s r?pido y preciso posible.', sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'Si tiene dudas consulteme.',sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    sprintf('\n'),...
    'Presione espacio para continuar']};
end