function [SUB] = choosedialog()

    d = dialog('Position',[300 300 250 400],'Name','SubjectInfo');
    
    Days = num2cell(1:31);
    Months = num2cell(1:12);
    Year = num2cell(2019:2119);
    Age = num2cell(1:120);
    a = 1
    
    Welcome_txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[15 80 210 300],...
           'String','Welcome!, Thanks for participating :)');
       
    Subject_ID_txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[-15 260 150 100],...
           'String','Subject_ID:');
       
    Subject_ID = uicontrol('Parent',d,...
           'Style','edit',...
           'Position',[32 320 150 20],...
           'String',{''});
       
   Session_txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[-20 215 150 100],...
           'String','Session:');
       
   Session = uicontrol('Parent',d,...
           'Style','edit',...
           'Position',[32 275 150 20],...
           'String',{''});
       
   Amount_Stimuli_txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[5 170 150 100],...
           'String','Amount_Of_Stimuli:');
       
   Stimuli = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[32 225 40 25],...
           'String',{'2';'3';'4'},...
           'Callback',@popup_callback);

   Day_txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[-30 123 150 100],...
           'String','Day:');
       
   Day = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[32 182 40 20],...
           'String',{Days{1,:}},...
           'Callback',@popup_callback);
       
   Month_txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[80 123 40 100],...
           'String','Month:');
       
   Month =uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[85 177 40 25],...
           'String',{Months{1,:}},...
           'Callback',@popup_callback);
    
   Year_txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[135 198 40 25],...
           'String','Year:');
       
   Year =uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[140 177 60 25],...
           'String',{Year{1,:}},...
           'Callback',@popup_callback);
       
   Age_txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[26 150 40 25],...
           'String','Age:');
       
   Age =uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[35 130 40 25],...
           'String',{Age{1,:}},...
           'Callback',@popup_callback);
       
   StartFrom_txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[28 100 60 25],...
           'String','StartFrom:');
       
   StartFrom = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[32 80 100 25],...
           'String',{'Perception';'Task'},...
           'Callback','delete(gcf)');

    Continuebtn = uicontrol('Parent',d,...
           'Position',[50 20 70 25],...
           'String','Ok',...
           'Callback','delete(gcf)');
       
       
    Cancelbtn = uicontrol('Parent',d,...
           'Position',[150 20 70 25],...
           'String','Cancel',...
           'Callback','close all');
       
    % Wait for d to close before running to completion
     uiwait(d);
     
       function popup_callback(event, varargin)
          idx = varargin.Value;
          popup_items = varargin.String;
          % This code uses dot notation to get properties.
          % Dot notation runs in R2014b and later.
          % For R2014a and earlier:
          % idx = get(popup,'Value');
          % popup_items = get(popup,'String');
          SUB{a,1} = char(popup_items(idx,:));
       end

end
